[package]
name = "edmipng"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
clap = { version = "4.5.17", features = ["derive"] }
crc = "3.2.1"
reqwest = { version = "0.12.7", features = ["blocking"] }
